backend:
  name: github
  repo: myminifactory/scan-the-world
  branch: jb-branch

site_url: https://myminifactory.com/scan-the-world
media_folder: static/assets
public_folder: /assets

collections:
  - name: pages
    label: Pages
    files:
      - label: Home Page
        name: home
        file: contents/pages/home.yml
        fields:
          - { name: title, label: Title, widget: string }
          - { name: intro, label: Intro, widget: text }
          - name: trends
            label: Trends
            widget: list
            fields:
              - { name: title, label: Title, widget: string }
              - { name: image, label: Image, widget: image }
              - { name: width, label: Width, widget: number, min: 1 }
              - { name: height, label: Height, widget: number, min: 1 }
              - { name: href, label: Link, widget: string, required: false }
              - { name: alt, label: Alt, widget: string, required: false }
      - label: About Page
        name: about
        file: contents/pages/about.yml
        fields:
          - { name: title, label: Title, widget: string }
          - { name: intro, label: Intro, widget: text }
          - { name: banner, label: Banner, widget: image }
          - name: team
            label: Team
            widget: list
            fields:
              - { name: title, label: Title, widget: string }
              - { name: position, label: Position, widget: string }
              - { name: quote, label: Quote, widget: string }
              - { name: photo, label: Photo, widget: image }
