backend:
  name: github
  repo: myminifactory/scan-the-world
  branch: jb-branch

site_url: https://myminifactory.com/scan-the-world
media_folder: static/assets
public_folder: /scan-the-world/assets

collections:
  - name: page
    label: Pages
    folder: contents/pages
    create: true
    fields:
      - { name: path, label: Path }
      - { name: banner_path, label: Banner Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
