backend:
  name: github
  repo: myminifactory/scan-the-world
  branch: jb-branch

site_url: https://myminifactory.com/scan-the-world
media_folder: static/assets
public_folder: /assets

collections:
  - name: pages
    label: Pages
    files:
      - label: Home Page
        name: home
        file: src/pages/index.md
        fields:
          - { name: templateKey, label: Template Key, widget: hidden, default: home-page }
          - { name: title, label: Title, widget: string }
          - { name: intro, label: Intro, widget: text }
          - name: trends
            label: Trends
            widget: list
            fields:
              - { name: title, label: Title, widget: string }
              - { name: src, label: Image, widget: image }
              - { name: href, label: Link, widget: string, required: false }
              - { name: alt, label: Alt, widget: string, default: "", required: false }
              - { name: float, label: Float, widget: select, options: [left, right] }
              - { name: width, label: "Width (px)", widget: number, min: 0, required: false }
              - { name: marginTop, label: "Margin top (px)", widget: number, min: 0, required: false }
      - label: About Page
        name: about
        file: src/pages/about/index.md
        fields:
          - { name: templateKey, label: Template Key, widget: hidden, default: about-page }
          - { name: title, label: Title, widget: string }
          - { name: intro, label: Intro, widget: text }
          - { name: bannerUrl, label: Banner, widget: image }
          - name: team
            label: Team
            widget: list
            fields:
              - { name: title, label: Title, widget: string }
              - { name: position, label: Position, widget: string }
              - { name: quote, label: Quote, widget: string }
              - { name: src, label: Photo, widget: image }
      - label: Contribute Page
        name: contribute
        file: src/pages/contribute/index.md
        fields:
          - { name: templateKey, label: Template Key, widget: hidden, default: contribute-page }
          - { name: title, label: Title, widget: string }
          - { name: intro, label: Intro, widget: text }
          - { name: bannerUrl, label: Banner, widget: image }
          - name: contributions
            label: Contributions
            widget: list
            fields:
              - { name: title, label: Title, widget: string }
              - { name: src, label: Image, widget: image }
              - { name: href, label: Link, widget: string, default: "#", required: false }
              - { name: alt, label: Alt, widget: string, default: "", required: false }
      - label: Uses Page
        name: uses
        file: src/pages/learn/uses/index.md
        fields:
          - { name: templateKey, label: Template Key, widget: hidden, default: uses-page }
          - { name: bannerUrl, label: Banner, widget: image }
          - name: uses
            label: Uses
            widget: list
            fields:
              - { name: title, label: Title, widget: string }
              - { name: src, label: Image, widget: image }
              - { name: intro, label: Intro, widget: text }

  - name: stories
    label: Stories
    folder: src/pages/learn/stories
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
      - { name: templateKey, label: Template Key, widget: hidden, default: storie-page }
      - { name: title, label: Title, widget: string }
      - { name: intro, label: Intro, widget: text }
      - { name: src, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
