backend:
  name: github
  repo: myminifactory/scan-the-world
  branch: jb-branch

site_url: https://myminifactory.com/scan-the-world
media_folder: static/assets
public_folder: /assets

collections:
  - name: page
    label: Pages
    folder: contents/pages
    create: false
    fields:
      - { name: title, label: Page Title }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: banner, label: Banner picture, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }
  - name: contribute
    label: Contribute Resources
    folder: contents/contribute-resources
    create: true
    fields:
      - { name: title, label: Resource Title, widget: string }
      - { name: resource_picture, label: Resource picture, widget: image }
      - { name: resource_link, label: Resource link, widget: string }
  - name: team
    label: Team
    folder: contents/team
    create: true
    fields:
      - { name: title, label: Member Title, widget: string }
      - { name: name, label: Name, widget: string }
      - { name: role, label: Role, widget: string }
      - { name: quote, label: Quote, widget: string }
      - { name: order, label: Order, widget: number, min: 0 }
      - { name: profile_picture, label: Profile picture, widget: image }
  - name: index
    label: Index Resources
    folder: contents/index-resources
    create: true
    fields:
      - { name: title, label: Resource Title, widget: string }
      - { name: image, label: Image, widget: image }
      - { name: width, label: Width, widget: number, min: 1 }
      - { name: height, label: Height, widget: number, min: 1 }
      - { name: alt, label: Alt, widget: string, required: false }
      - { name: href, label: Href, widget: string, required: false }
      - { name: order, label: Order, widget: number, min: 0 }
